### ISSUE TITLE
Logout function needed!

### ISSUE THREAD

**Issue by cwkean87** [portapipe/Login-GroceryCrud#1]
Dear author,

Thank you for this piece of work. I have succesfully installed in into my ci project and it works great. But then realized that there is no logout controller. Would you mind to add one to your work please?

On the other hand, how could i add a md5 password to my users table by default?

Thank you again and in advance.

Cheers

**Comment by portapipe** [comment]
Hi @cwkean87.
There is the logout page `/login/logout` and even a function `$this->login_model->logout()` where you can pass a 'true' argument to enable the redirect to the login page 😃 
For the md5 question you have to enable the md5 encrypt option into the Login.php controller (config on the top).
If you are asking how to enable md5 in GroceryCrud you can find a great example in the [GC documentation here](http://www.grocerycrud.com/documentation/options_functions/callback_before_insert)

**Comment by cwkean87** [comment]
Thanks. Got that, my bad. Ya it's not a valid issue. Any chance that you could add a session control for the project please?

**Comment by portapipe** [comment]
No problem. What do you mean with a session control?

**Comment by cwkean87** [comment]
Such as auto-log user out if the browser/tab is closed?

**Comment by portapipe** [comment]
This system use the php.ini sessions so the login session are closed automatically after some times (like a long pc shutdown) or after IP change (or a regular logout). It works as it should out-of-the-box 😃

**Comment by cwkean87** [comment]
I see. i am new in ci project rev. Please pardon me. Your code works like a charm dude. Cheers

**Comment by portapipe** [comment]
Thanks 😄 
Let me know any bug you'll find (if there are some).
Have a nice code!

**Comment by cwkean87** [comment]
sure thing 👍
