### ISSUE TITLE
Defining multiple permission groups to a user

### ISSUE THREAD

**Issue by yusuf-mutlu** [portapipe/Login-GroceryCrud#12]
It would be awesome if we could define multiple permission groups to a user. Thanks.

**Comment by yusuf-mutlu** [comment]
And also thanks for this simple and awesome login system. :)

**Comment by portapipe** [comment]
You're welcome :)
For now you can create as many group as you want.
Multiple permission can be used for single tables BUT! What is more important than the other? The true or false one? Because you can have conflicts and don't know what is messing your stuff up... is that correct?

**Comment by yusuf-mutlu** [comment]
Technically we may have conflicts and messing issues. This is our developer view. :) But if we look of system manager's view, we may want to define two permission groups to a one user. That way it looks easier to configure permission managements.

I am also not sure about what point of look is right. :)

**Comment by portapipe** [comment]
Well if you select a "ID Only" field in the first group and let it disabled in the second one, which one will be used?

**Comment by yusuf-mutlu** [comment]
Now i got the point and cleared my mind. :) Thanks very much.

**Comment by portapipe** [comment]
You're welcome :) If you have any doubt just ask ;)
