### ISSUE TITLE
Permission Management

### ISSUE THREAD

**Issue by Essakini** [portapipe/Login-GroceryCrud#21]
Hi

I have tried the code and it works until the system needs to verify the permission after the call in the controller/ login folder:
[ ] $crud = $this->login_model->check($crud);
In the login_model the function keeps echoing line 64
if(!$table){ echo "You need to pass a table to 'this->login_model->extractPermission()' as third parameter to use the current logged user permissions!";die;}

Can please anyone clarify which table has be to included and where ? (crud_permissions or crud_users?)

to me it seems I need to add the table in the function public function extractPermission($what,$permission=false,$table=false) but it doesn't work

if I comment the link `$crud = $this->login_model->check($crud); ` in the controller login folder, then it works but any users can access the user permission table. 

What am I missing?

**Comment by portapipe** [comment]
Hi Essakini and thanks for your question,
did you check the wiki?

https://github.com/portapipe/Login-GroceryCrud/wiki/Table-Permission-Management-(GRID)

Did you use the line "$this->crud->setTable("...");" in the $crud variable?

**Comment by Essakini** [comment]
Hi  Portapipe,

Thank you for the reply, Yes I tried the link provided and I am still using it to try to understand.

Sorry for the long text, I tried my best to explain the issue as short as I could.

I have found the solution to the previous query just last night. Basically, I had to add the **crud_users** table in the model_log file so that I won't get the `if(!$table){ echo "You need to pass a table to 'this->login_model->extractPermission()' as the third parameter to use the current logged user permissions!";die;}`

The modification was made here: `if(!$this->extractPermission("RL",false,'**crud_users'**)) $crud->unset_list();` Line 136 in the `public function check($crud,$author=false)` 

Now I can access the website based on the crud_user permissions but this limits the crud_user permissions table (I think) because when setting the permission in the crud_permissions table for a group of tables, the result is not reflected for only the selected table but it applies for whole table group. 

For example, if a crud_user logged with permission 1, then the user has full access even if I denied access to add or edit certain tables in the crud_permission table. 

On the other hand, if the user logged in with permission 2, whatever is set in the crud_permission is applied to the whole group of tables (meaning I cant have edited only for one table because it will show the edit button to the whole table group except for crud_permissions table).

I don't understand where I should write the condition so that the crud can identify the permissions.

I use 2 controllers, the Log controller and my main model. does it mean that the condition must be included in the main controller along with `$crud = $this->login_model->check($crud);` where the tables are called or in the log controller? 

Did you use the line "$this->crud->setTable("...");" in the $crud variable? yes for each table in the group in the main controller.

**Comment by portapipe** [comment]
My suggestion is to not edit the code. This code is used in several active websites so it's working, is just to know how to use it.
The logic is that you have to create all your $crud = new blablabla... code, then pass the $crud to the check function and then call the render.

You must use a users table that fits the needs (it must have a 'permissions' field).
An example:

```php
$crud = new grocery_CRUD();
 
$crud->set_table('blog_posts');

$crud = $this->login_model->check($crud,"users");
//before declaring the output variable!
$output = $crud->render;
```

Adding the 

```php
$crud->set_relation('permissions','crud_permissions','name');
```

in the users table, you'll see all your groups in your dropdown menù.
So your problem should be fixed with the second parameter of the check function.

You should use this just in one controller, nothing more is required, and use just the code above. If you are encountering other issues please paste your code so we can check together :)

**Comment by Essakini** [comment]
Thank you for your swift reply!
I attempted to restore the code as you suggested but simply it doesn't work for me because when I do  `$crud = $this->login_model->check($crud,"users");` it says not Colum users found (users as example)

Surly I missing something or implemented it wrong. 

I attached a table as one example so not to bother you much, if required I can upload both the controllers files.

This is the main controller we the table views:
`public function orchard()
	{	
		//getting the table 
		$crud = new grocery_CRUD();
		$crud->set_theme('datatables');
		
		$crud->set_table('orchard');
		$crud->set_subject('orchard');
		

		$crud->columns('orchardID', 'LocationName');
		$crud->set_relation('LocationName', 'variety', 'fruitName'); // relation with another table to get the Location name
		$crud->fields('orchardID', 'LocationName');
		$crud->required_fields('orchardID', 'LocationName');
		
		$crud->display_as('LocationName', 'Location');
		//$crud->unset_add();// function if its a sale agent account
		$crud = $this->login_model->check($crud); // here if include the name or id it gives me an error that the column doesn't exist
		$output = $crud->render();
		$this->orchard_output($output);
	}
	
	function orchard_output($output = null)
	{
		$this->load->view('orchard_view.php', $output);
	}
	`

in the login controller I have the below: 

//page to manage all the permissions
	//Yes, this IS the page of the permissions
	```
public function manage_permissions(){
		
		if(!$this->login_model->isLogged()){ redirect(base_url()."login"); return;}
		
		$this->createDBTableForPermissions();
		
		$this->load->library('grocery_CRUD');
		
		$crud = new grocery_CRUD();
		$crud->set_table('crud_permissions');
		$crud->set_subject('Permission Management');

		//$crud->set_relation('permissions','crud_permissions','name');
		
        $crud->columns('id');
		//$crud->set_relation('name','crud_permissions','name');
		$crud->set_relation('id', 'crud_users', '{id} - {username}');
		$crud->required_fields('id');
		$crud->fields('id', 'permissions');
		$crud->display_as('id', 'ID - Username');
		$crud->unset_read();

		$crud->callback_field('permissions',array($this,'create_permissions_grid'));
		$crud->callback_before_insert(array($this,'elaborate_the_grid_then_update'));
		$crud->callback_before_update(array($this,'elaborate_the_grid_then_update'));
		$crud = $this->login_model->check($crud);
		$output = $crud->render();
		$this->permission_output($output);
		

	}
	
	function permission_output($output = null)
	{
		$this->load->view('header.php', $output);
		$this->load->view('managePermissions.php', $output);
	}
```

In the login_model under check I have:
`//The function that MUST be used to filter the CRUD table based on the permissions
	public function check($crud,$author=false){
		$state = unserialize(
			preg_replace(
				'/^O:\d+:"[^"]++"/', 
				'O:'.strlen("portapipe").':"portapipe"',
				serialize($crud)
			)
		);
		
		$state = json_encode((array)$state);
		$state2 = strpos($state,'basic_db_table":"');
		$state = str_replace('basic_db_table":"','',substr($state, $state2));
		$state2 = strpos($state,'"');
		$table = substr($state, 0, $state2);
		if(!$this->extractPermission("RL",false,'crud_users')) $crud->unset_list();  // if not used crud_users, I get error must provide a table as 3rd parameter 
		if(!$this->extractPermission("RS",false,'crud_users')) $crud->unset_read();
		if(!$this->extractPermission("D",false,'crud_users')) $crud->unset_delete();
		if(!$this->extractPermission("A",false,'crud_users')) $crud->unset_add();
		if(!$this->extractPermission("E",false,'crud_users')) $crud->unset_edit();
		if(!$this->extractPermission("D",false,'crud_users')) $crud->unset_delete();
		
		if($author) $crud->where($author,$this->id());
		
		return $crud;
	}`

I really hope I can understand how the system connects

**Comment by portapipe** [comment]
Is the 'orchard' table has a "user" or I suggest an "authour" column?
```php
$crud = $this->login_model->check($crud,"user/author"); // the second parameter should the name of the author's field in the table you want to add it, but it's not mandatory!
$output = $crud->render();
$this->orchard_output($output);
```
You should add the 'author' column there, so people can see just the data they've added (so they can eventually edit o delete it, based on the actions you want to give in the permission's grid) if the "only ID" option is selected, but it's not mandatory, so the issue should be elsewhere.
Plus: are you using Codeigniter 3 or 4?

**Comment by Essakini** [comment]
There is not an author column on the Orchard table (just those 2): with the users being (grower) can edit,  (head-grower) full right, and (user) one can only view.

I followed your suggestion to Not change the code so I restored the log_model file and log controller. I end up with the issue I had a the beginning only when trying accessing the permission table with any account. The message is: `"You need to pass a table to 'this->login_model->extractPermission()' as third parameter to use the current logged user permissions!`

While about the table, the (head-grower) has full permission on the orchard table and the (user) has the same access to the (grower). 

I am using Codeigniter 4

**Comment by Essakini** [comment]
I was able to resolve the issue. the permissions column in the crud_users table acts as id identifier so if any user has the same permission then it gives the same authorities when referring in the crud_permissions table.
.

**Comment by portapipe** [comment]
Good, well done!
