### ISSUE TITLE
HELP! Permission Management Error.

### ISSUE THREAD

**Issue by cwkean87** [portapipe/Login-GroceryCrud#3]
Hi there,i got this error when intended to manage the permission using the url as instructed:

URL: domain.com/subdomain/login/manage_permissions

A Database Error Occurred

Error Number: 1064

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1

SELECT permissions FROM crud_permissions WHERE id =

Filename: models/Login_model.php

Line Number: 62

Please help. Thanks in advance.

Cheers

**Comment by portapipe** [comment]
I think you need to give more informations like:
- how is your htaccess?
- how is your CI config file? (base url and other url-related stuff)?
  Please use sites like www.pastebin.com to send the code

**Comment by cwkean87** [comment]
hi, my base url is `$config['base_url'] = 'http://domain.com/sub';` and .htaccess is as below.

```
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /sub/

RewriteCond %{REQUEST_URI} ^system.*
RewriteRule ^(.*)$ /index.php?/$1 [L]

RewriteCond %{REQUEST_URI} ^application.*
RewriteRule ^(.*)$ /index.php?/$1 [L]

RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ index.php?/$1 [L]
</IfModule>
```

**Comment by portapipe** [comment]
did you login with the 'admin' - 'admin' user?

**Comment by cwkean87** [comment]
No i did not. And now the problem solved after i logged in with an admin account. Thank you for your prompt support.

Cheers dude.

**Comment by portapipe** [comment]
You're welcome :) First login always with the 'admin' user :)

**Comment by cwkean87** [comment]
Ya, but my itchy fingers edited the login credential and forgot to make it an admin user. 👍
