### ISSUE TITLE
On initial install The requested URL /login/makeLogin was not found on this server

### ISSUE THREAD

**Issue by jswolcott** [portapipe/Login-GroceryCrud#7]
This is a local URL for devel on this machine and not an actual domain

The initial login page displays perfectly. However after attempting to login i am redirected to https://bigfish.testsss.com/login/makeLogin and get:

The requested URL /login/makeLogin was not found on this server.

**Comment by portapipe** [comment]
That's weird. I had no complains about this kind of stuff.
Maybe you can check your .htaccess or you maybe forgot something or changed the way CI manage the routes (?)
Btw check the LGC controller, there is a couple of lines you need to set up.

**Comment by jswolcott** [comment]
changed line 25 of views/login.php

>form class="form col-md-12 center-block" action="<?=base_url();?>**index.php**/login/makeLogin" method="post"> 

Since I am new to both codeigniter grocery crud and your login this was a default from the up and going tutorials on codeigniter and grocery crud. The index.php addition was needed to get going with default settings.

This looks like a great project. Thanks for sharing your work!

**Comment by portapipe** [comment]
Glad to hear that you've fixed :) Happy to help the community and you @jswolcott 
Happy new year!
