### ISSUE TITLE
Path issue

### ISSUE THREAD

**Issue by wellsprings** [portapipe/Login-GroceryCrud#8]
Hi Portapipe,

I am not sure whether I got this correct.

I loaded the CI3.12 and GroceryCrud and your Login-GC files accordingly to 45.76.150.27/mybiz/ci312 folder.

In the CI312 config.php file, the path is set to:

*/
$config['base_url'] = 'http://45.76.150.27/mybiz/ci312/';

/*

In GC-Login, Login.php file, the path is set to:

<?php
$loginConfig = array(
	"Page After Login" =>                 
        "http://45.76.150.27/mybiz/ci312/index.php/examples/",
	"Error Message" => "Your Username or Password are incorrect!",
	"Use MD5 Encryption" => false,
	"Show Permission Management Tips" => true, //suggested

After going to 45.76.150.27/mybiz/ci312/index.php/login and putting in the details, the url is resolved to
http://45.76.150.27/mybiz/ci312/login/makeLogin.

I have tried many different combinations of the path in the Login.php and I cannot get the url to resolve to 45.76.150.27/mybiz/ci312/index.php/examples.

Where did I go wrong?   Thanks for your time.

peter.

**Comment by portapipe** [comment]
I think you miss the htaccess file. Add this lines to your .htaccess file:
```
RewriteEngine on
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ index.php/$1 [L,QSA] 
```
Plus I suggest you to remove the "index.php" from this config line:
`$config['index_page'] = "index.php";`
to be
`$config['index_page'] = "";`

This is the working link that make this code above the solution: http://45.76.150.27/mybiz/ci312/index.php/login/makeLogin

**Comment by wellsprings** [comment]
Hi Portapipe, many thanks for your help. It's still not working and I have taken a break for a while to celebrate Chinese New Year.

Today as I reading some CI tutorial, now I understand your intention of removing the index.php. I will fiddle with the coding till I resolve this.

Peter
