### ISSUE TITLE
Login.php wrong tag at line 170

### ISSUE THREAD

**Issue by BaginovPM** [portapipe/Login-GroceryCrud#9]
To start writing PHP code line 170 contains "<?" instead of "<?php".

**Comment by portapipe** [comment]
"<?" is the short-tag of "<?php" and servers that doesn't enable that are wrong configured.
Anyway you should edit it 😄

**Comment by BaginovPM** [comment]
Oops, sorry...
Thanks

**Comment by portapipe** [comment]
No problem :)
